### ISSUE TITLE
Migrate OWASP ZAP slave from rht-labs

### ISSUE THREAD

**Issue by springdo** [redhat-cop/containers-quickstarts#100]
As per the title; in labs we have the owasp-zap jenkins slave in a separate repo. Wasn't caught as part of #78.  Are we cool to lift and shift it to here with the other `jenkins-slave-*`? 

https://github.com/rht-labs/owasp-zap-openshift

I'm happy to do the leg work on it!

**Comment by springdo** [comment]
@tompage1994 I think said he would look at this today

**Comment by pabrahamsson** [comment]
Fixed by #105
