### ISSUE TITLE
Add Erlang Jenkins Slave and Erlang S2I image

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/containers-quickstarts#101]
# Overview
Add the ability for Jenkins to run a slave which can build Erlang applications using [Rebar3](https://www.rebar3.org/). Also, add an S2I image build which can convert an Erlang release to a runnable container image using Rebar3

# Acceptance criteria
* A new Jenkins slave image which has Rebar 3 and Erlang/OTP installed for use with creating a "release"
* A new S2I image which can take an Erlang release created via Rebar 3 and create a runnable container

**Comment by garethahealy** [comment]
https://github.com/redhat-cop/containers-quickstarts/pull/117
