### ISSUE TITLE
Slave builds are broken

### ISSUE THREAD

**Issue by springdo** [redhat-cop/containers-quickstarts#104]
Since #87 was fixed for just one image `jenkins-slave-golang` the `jenkins-slave-generic-template.yml` has been defaulted to look for a `Dockerfile.rhel7`. This means instructions for over ridding this need to be included on the README of each slave that does not have a `Dockerfile.rhel7` or a `Dockerfile.rhel7` version needs to be included with each slave.  

Also any connecting repositories using the `jenkins-slave-generic-template.yml` template via the `openshift-applier` should also be updated / version pinned accordingly.

**Comment by pabrahamsson** [comment]
Thank you @springdo 
I'll take a look at this and update where necessary.
