### ISSUE TITLE
Evaluate Phabricator in OpenShift

### ISSUE THREAD

**Issue by lpsantil** [redhat-cop/containers-quickstarts#110]
Phabricator competes in the same space as Github, Gitlab, Gogs, Jira/Confluence/HipChat/Trello/Bitbucket, etc.  Phabricator is in use by organizations like Mozilla, Wikimedia Foundation, Facebook, etc.  It was originally developed by Facebook [0].  It includes functionality to support Code Reviews, Workboards (Kanban boards), Task Management, Wikis, and Chat [1].

[0] https://en.wikipedia.org/wiki/Phabricator
[1] https://phacility.com/phabricator/

**Comment by pabrahamsson** [comment]
Hi @lpsantil, are you looking for someone to create a quickstart for Phabricator or for something beyond that?

**Comment by pabrahamsson** [comment]
@lpsantil can you please comment on my question above?

**Comment by lpsantil** [comment]
Whoops...apologies.  I missed your earlier question.

You're correct; looking for a quickstart.  I thought it would complement the gitlab-ce & gogs well to have another option.

**Comment by leoluk** [comment]
There's this: https://github.com/leoluk/openshift-phabricator

It include all pieces necessary for running Phabricator in production (including SSH), uses S2I builds and is a good OpenShift showcase in general. Also, lots of nss_wrapper trickery to get Git and SSH working.
