### ISSUE TITLE
ZAP slave fails to find Username/Home because of random start-up user in OpenShift

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/containers-quickstarts#138]
Need to allow for the `/etc/passwd` file to be updated on startup so that the randomly chosen UID from OpenShift is integrated into `/etc/passwd`.

**Comment by lpsantil** [comment]
@InfoSec812 That'll take root user and an SCC to implement in OCP.  Is that what you really want?

**Comment by syvanen** [comment]
For example the Jenkins we run on OpenShift does this /etc/passwd trick and it's also documented at https://docs.openshift.com/container-platform/3.5/creating_images/guidelines.html#openshift-specific-guidelines

**Comment by syvanen** [comment]
I'm a bit confused. As this is based on Jenkins-slave container image, it already has this functionality inside `/usr/local/bin/run-jnlp-client` -script.

If I run the current Image without #139 I get an user id resolved:

```
jenkins-slave-zap-lpf4p is offline
Running on jenkins-slave-zap-lpf4p in /tmp/workspace/Test
[Pipeline] {
[Pipeline] stage
[Pipeline] { (test zap)
[Pipeline] sh
[Test] Running shell script
+ id
uid=1001380000(jenkins) gid=0(root) groups=0(root),1001380000
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```
Also this container image is used successfully in a pipeline:
https://rht-labs.github.io/enablement-docs/#/5-non-functionals-strike-back/README?id=part-1-add-security-scanning-to-the-pipeline

So what was the original problem you were trying to solve?

**Comment by garethahealy** [comment]
@InfoSec812 ; is this still a problem? the above seems to suggest not.
