### ISSUE TITLE
Feature Request: Build a Node.js 6 s2i image

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/containers-quickstarts#14]
Probably makes sense to start here: https://github.com/sclorg/s2i-nodejs-container

**Comment by etsauer** [comment]
Trello card created: https://trello.com/c/eCGcZrDS/20-feature-request-build-a-node-js-6-s2i-image-14

**Comment by etsauer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature Request: Build a Node.js 6 s2i image #14](https://trello.com/c/eCGcZrDS/20-feature-request-build-a-node-js-6-s2i-image-14)

**Comment by davgordo** [comment]
I think that the standard OpenShift Node.js s2i image now supports version 6.

**Comment by sabre1041** [comment]
@davgordo yes you are correct. Thanks for the heads up

Closing issue
