### ISSUE TITLE
Create Selenium Jenkins Agents for Chrome and Firefox

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/containers-quickstarts#141]
As a DevOps team member, I need to be able to run Selenium tests from within Jenkins pipelines. In order to run Selenium tests, I need a Jenkins Agent which can execute Google Chrome and Firefox web browsers in a "headless" environment using Xvfb running as a non-root user.

**Comment by raffaelespazzoli** [comment]
@InfoSec812 did you see this https://github.com/redhat-cop/container-pipelines/tree/master/cucumber-selenium-grid ?
Let me know if it helps with your use case.

**Comment by InfoSec812** [comment]
@raffaelespazzoli Zalenium has 2 things which make it not work for the use case we have with our current customer:

1. It requires special SCCs to work
2. It will not work with Zed Attack Proxy for Passive Analysis
