### ISSUE TITLE
Jenkins slave images not tied to OCP release

### ISSUE THREAD

**Issue by makentenza** [redhat-cop/containers-quickstarts#145]
Right now we are using 'latest' tag for every single Jenkins Slave container image. We should use the corresponding existing tag aligned with the OCP version and the 'cut release' we use for this repository. We have recently identified some issues while using the 'latest' tag

**Comment by garethahealy** [comment]
@makentenza ; is this still an issue or can be closed? i checked a few of the slaves and they all point to a tagged version:
- https://github.com/redhat-cop/containers-quickstarts/blob/master/jenkins-slaves/jenkins-slave-mvn/Dockerfile#L1
