### ISSUE TITLE
Include Hygieia container 

### ISSUE THREAD

**Issue by jarcher** [redhat-cop/containers-quickstarts#160]
Looking for a ready to go Hygieia OCP template...

**Comment by pabrahamsson** [comment]
@jarcher does our [Jenkins with Hygieia](https://github.com/redhat-cop/containers-quickstarts/tree/master/jenkins-masters/hygieia-plugin) give you what you're looking for?

**Comment by garethahealy** [comment]
@jarcher ; does @pabrahamsson response answer your question? can this be closed?
