### ISSUE TITLE
Eclipse che

### ISSUE THREAD

**Issue by roridedi** [redhat-cop/containers-quickstarts#165]
Any plans for adding an eclipse che container?

**Comment by sherl0cks** [comment]
Theia is an upstream IDE that will replace the existing Che GWT IDE. Theia doesn't handle shared workspaces, pair programming etc. 

Long term, the product strategy is around the full ecosystem of Che, so we need to be careful about investing too much in Theia alone.

**Comment by pcarney8** [comment]
+1 makes sense. I figured it would easy to migrate the work already done with theia from rht-labs to here. Then update to Che later on

**Comment by sherl0cks** [comment]
sure - that makes sense to me. just making sure we have the larger context in mind when making these choices.

**Comment by roridedi** [comment]
I think this can be closed in favor of a che operator.
