### ISSUE TITLE
Pin SonarQube version for each release

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/containers-quickstarts#186]
Currently, the SonarQube image is always the "latest" version of SonarQube, thus there is no guarantee that any given release of this project will have the same version of SonarQube.

From https://github.com/rht-labs/labs-ci-cd/issues/64

**Comment by InfoSec812** [comment]
This needs to be addressed in [Labs CI/CD](https://github.com/rht-labs/labs-ci-cd), to allow that we need to add a new Docker build template which allows for overriding the `FROM` clause of the Dockerfile. I will submit a PR for that under this issue number.
