### ISSUE TITLE
Use RHEL Jenkins Slave base to avoid permissions issues in OCP

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/containers-quickstarts#195]
https://github.com/redhat-cop/containers-quickstarts/blob/5f9bcebedfd284e506a5960b7e6fe9f0d6020402/jenkins-slaves/jenkins-slave-ruby/Dockerfile#L1

This older CentOS slave has an outdated OC client and incorrect permissions for newer OpenShift environments

**Comment by syvanen** [comment]
The other Jenkins Slave have typically have it's own RHEL Dockerfile called `Dockerfile.rhel7` (Reference: https://github.com/redhat-cop/containers-quickstarts/tree/master/jenkins-slaves/jenkins-slave-ansible).
Should we stay consistent with this `Dockerfile` and `Dockerfile.rhel7` model?
