### ISSUE TITLE
List of test cases to verify cluster functionality

### ISSUE THREAD

**Issue by tomgeorge** [redhat-cop/containers-quickstarts#197]
We are setting up CI for containers-quickstarts, and need a list of test cases to run through.  This can be a place to put different test cases we would like to see.

+ API server is available
+ Default routes are available
+ Registry is available
+ etcd is running
+ fluentd is running

**Comment by etsauer** [comment]
this is addressed in https://github.com/redhat-cop/openshift-toolkit/tree/master/validation
