### ISSUE TITLE
Update jenkins-slave-npm to work on OCP 4.x

### ISSUE THREAD

**Issue by pabrahamsson** [redhat-cop/containers-quickstarts#226]

**Comment by tylerauerbeck** [comment]
I'm going to use this issue to kind of cover all of our jenkins-slaves. I see that currently we're targeting the RHEL 7 UBI. I'm wondering whether we should target the RHEL 8 UBI outright or assuming that we'll need to support RHEL 7 and 8 for the near term, should we move to Dockerfile being based on the RHEL 7 UBI and then just have a separate (Dockerfile.rhel8) file to support both versions (and thereby dropping the use of our centos image that we're currently using inside of `Dockerfile`).

cc/ @redhat-cop/day-in-the-life

**Comment by pcarney8** [comment]
@tylerauerbeck I personally like the idea of moving `Dockerfile.rhel7` to UBI 7 and then just adding `Dockerfile.rhel8`. Remind me though, UBI 7 can be used almost like a CentOS image without the need to subscriptions correct?

**Comment by etsauer** [comment]
@tylerauerbeck @pcarney8 @pabrahamsson @sabre1041 what would the reason be to have both a UBI 7 and 8 version? The purpose of UBI is to be able to stop maintaining different dockerfiles for upstream and enterprise, and be able to have one image that can be both supported and made public. I would like to see us convert all of the slave images to UBI and maintain one version of the image for each. Unless we have a reason not to, I would vote to just go straight to UBI 8

**Comment by tylerauerbeck** [comment]
Per our discussion today, it sounds like the direction we're headed is to just target UBI8 first and then revisit any use cases that may require UBI7 moving forward. @etsauer @sabre1041 @oybed Feel free to correct me if I misunderstood.

As long as there are no objections, @pabrahamsson would you be able to update your PR's to target UBI8 when you get a chance?

**Comment by oybed** [comment]
@tylerauerbeck you got it right - looking forward to have some working slaves on UBI8

**Comment by pabrahamsson** [comment]
I've on PTO and missed the above discussion but this is exactly the conversation I wanted to happen (and also the direction I was hoping for). I'll will update #222 to have one Dockerfile based on UBI8.
Thank you for your feedback @tylerauerbeck @etsauer @oybed @pcarney8

**Comment by garethahealy** [comment]
@pabrahamsson ; is anything else needed on this issue? or dos the merged PRs allow it to be closed?
