### ISSUE TITLE
zap scanner does not work cuz all the .py files are really old and some other reasons too

### ISSUE THREAD

**Issue by springdo** [redhat-cop/containers-quickstarts#236]
We have been trying to update the DO500 course content and hit several issues with the zap slave. The image builds fine, but errors like crazy when you try and run a scan. 

I am working on a "🔨fix 🔨" for this, it's a bit .... interesting .... but should be along shortly

**Comment by InfoSec812** [comment]
@springdo - @haithamshahin333 and @InfoSec812 have done a bunch of work on this and submitted PRs a LONG time ago to resolve these issues, but they are held up in PR hell.

**Comment by garethahealy** [comment]
Currently two PRs open for this:
- https://github.com/redhat-cop/containers-quickstarts/pull/237
- https://github.com/redhat-cop/containers-quickstarts/pull/219
