### ISSUE TITLE
Update jenkins-slave-image-mgmt to work on UBI

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/containers-quickstarts#238]
Currently we cannot convert jenkins-slave-image-mgmt to the UBI based slave image because skopeo is not available in the ubi rpm repos. I've opened a bug. https://bugzilla.redhat.com/show_bug.cgi?id=1737620

**Comment by garethahealy** [comment]
bugzilla has been closed due to no plans to support skopeo via UBI repos. if we do plan to move to ubi, i am guessing skopeo will need to be enabled via a customer repo. possibly linking to this issue:
- https://github.com/redhat-cop/containers-quickstarts/issues/112
