### ISSUE TITLE
Add support for Nexus OpenShift/Kubernetes plugin integration

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/containers-quickstarts#259]
Create Dockerfile, BuildConfig, DeploymentConfig, Route(s), etc... to allow deployment of Sonatype Nexus using the new OpenShift/Kubernetes plugin.

**Comment by garethahealy** [comment]
Related to: https://github.com/redhat-cop/containers-quickstarts/pull/260

**Comment by InfoSec812** [comment]
Still valid and I am still working on this as I have time.
