### ISSUE TITLE
Rabbitmq image failes to build

### ISSUE THREAD

**Issue by gil0109** [redhat-cop/containers-quickstarts#262]
During build, it hits this part and fails on retrieving keys..

```
GNUPGHOME=/tmp/tmp.eh8ke7c0iw
--
  | + gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 0A9AF2115F4687BD29803A206B73A36E6026DFCA
  | gpg: keyring `/tmp/tmp.eh8ke7c0iw/secring.gpg' created
  | gpg: keyring `/tmp/tmp.eh8ke7c0iw/pubring.gpg' created
  | gpg: requesting key 6026DFCA from hkp server ha.pool.sks-keyservers.net
  | gpg: keyserver timed out
  | gpg: keyserver receive failed: Keyserver error
  | Removing intermediate container 3583363f9b49
```
Any chance we can get an updated Dockerfile with rabbitmq version 3.7.19?

**Comment by pabrahamsson** [comment]
Hi @gil0109,

I'm not sure the issue you're seeing is related to the rabbitmq build but rather to your environment (or the remote key server) as the connection is timing out.

Can you please make sure your environment is indeed able to get the key from `ha.pool.sks-keyservers.net`?

I've tested the build successfully both locally and in OpenShift.
As for upgrading the version, please open a new issue.

**Comment by gil0109** [comment]
Thanks, it seemed to work now.  But now I get this error:

'''
+ curl -LO https://github.com/rabbitmq/erlang-rpm/releases/download/v22.1.3/erlang-22.1.3-1.el7.centos.x86_64.rpm
--
  | % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  | Dload  Upload   Total   Spent    Left  Speed
  | 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100     9    0     9    0     0      8      0 --:--:--  0:00:01 --:--:--     8100     9    0     9    0     0      8      0 --:--:--  0:00:01 --:--:--     8
  | + rpm -Uvh ./erlang-22.1.3-1.el7.centos.x86_64.rpm
  | error: open of Not failed: No such file or directory
  | error: open of Found failed: No such file or directory
'''

**Comment by gil0109** [comment]
Strange, I can curl the site but still receiving an error when requesting a key.  I will check with our networking folks.  Thanks for your input.
