### ISSUE TITLE
Convert jenkins-slave-image-mgmt to UBI, or remove it if its no longer needed.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/containers-quickstarts#275]
@redhat-cop/day-in-the-life @itewk what do you guys think? Is there any image out there already that provides skopeo?

**Comment by etsauer** [comment]
If we do convert to UBI, it also needs to be added to the CI for the repo.

**Comment by itewk** [comment]
i dont know of another one that does, so this is always my go to

**Comment by pabrahamsson** [comment]
I briefly looked into building this image with UBI a while ago and IIRC there wasn't a straightforward way to get a skopeo binary onto a UBI image. But I think we should revisit this issue. Thank you for opening it @etsauer

**Comment by garethahealy** [comment]
i currently use the following image for the pipeline library tests:
- https://github.com/redhat-cop/pipeline-library/blob/master/.applier/group_vars/seed-hosts.yml#L35-L40

As the image in quay has no tags:
- https://quay.io/repository/redhat-cop/jenkins-slave-image-mgmt?tab=tags

Seems to be failing to build but i don't have access to view logs as to why on quay.

**Comment by garethahealy** [comment]
Also, seems we have a duplicate:
- https://github.com/redhat-cop/containers-quickstarts/issues/238
