### ISSUE TITLE
Use a bot to update Dockerfile froms

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/containers-quickstarts#279]
re: https://github.com/redhat-cop/containers-quickstarts/commit/58e71a0070148ecf29846ba127df221a012f56f7

since i raised the above, it got my thinking. could we use a bot to do this? looks like dependabot supports docker:
- https://dependabot.com/docker/

@pabrahamsson ; thoughts around general idea?

**Comment by pabrahamsson** [comment]
@etsauer @sabre1041 am I good to add dependabot to the redhat-cop org?

**Comment by etsauer** [comment]
@pabrahamsson @garethahealy I like it.

**Comment by pabrahamsson** [comment]
First try and I think we might need some additional tweaking
https://github.com/redhat-cop/containers-quickstarts/pull/295
