### ISSUE TITLE
Update published SonarQube image on Quay.io

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/containers-quickstarts#285]
The SonarQube image has been updated to include improvements from #282 and #283. We need to rebuild the image and publish the updated image to Quay.io.

**Comment by InfoSec812** [comment]
@mcanoy Issue as requested.

**Comment by pabrahamsson** [comment]
@InfoSec812 I've created https://quay.io/repository/redhat-cop/sonarqube
