### ISSUE TITLE
Question: should these jenkins slaves work on 3.11 cluster?

### ISSUE THREAD

**Issue by jzr1991** [redhat-cop/containers-quickstarts#392]
I'm trying to upgrade the base images I'm using for my Jenkins slaves to the origin-jenkins-base-agent from a previous generic centos7 Jenkins slaves.

I'm trying to build the jenkins-slave-golang inside my Openshift 3.11 cluster but constantly get permission errors when it's trying to do things like write to /usr or making a directory.

It worked perfectly fine previously where it was the exact same install but just on top of a different base image. Yum installs seem to work ok.

Anyone any ideas?

Thanks

**Comment by garethahealy** [comment]
@jzr1991 ; that's sounds like due to a change on the 4.x agents. I'll try and dig out the PR.

**Comment by jzr1991** [comment]
@garethahealy This is likely my ignorance but I can't figure out how that change applies to my issue/what it means?
