### ISSUE TITLE
ubi8-asciidoctor does not build due to kindlegen and asciidoctor-epub3

### ISSUE THREAD

**Issue by nesanton** [redhat-cop/containers-quickstarts#408]
Container does not build because `kindlegen` and `asciidoctor-epub3` are no longer available to from amazon. See https://github.com/tdtds/kindlegen/issues/42

Do we need them anyway?

**Comment by nesanton** [comment]
@itewk

**Comment by buuhsmead** [comment]
kindlegen , I assume we live without. 
asciidoctor-epub3, is a / was a item which belongs to the asciidoctor suite.
Will have  a look at both

**Comment by pabrahamsson** [comment]
@buuhsmead have you had a chance to look into this?

**Comment by buuhsmead** [comment]
@pabrahamsson Sorry no, busy with customer work. Will put on the list for this week / weekend.

**Comment by buuhsmead** [comment]
@nesanton @pabrahamsson I think this is an old issue. 
The image just builds fine. And epub3 is installed and available.
Kindlegen is not an option (any) more.
The current content of this image is fulfilling its primary objective to generate pdf's. 
I would suggest to close this issue.

**Comment by nesanton** [comment]
Uuu, sorry, I should have closed it. Correct, it's no longer an issue for exactly the reasons @buuhsmead is giving
