### ISSUE TITLE
Need a new s2i builder image that includes gradle

### ISSUE THREAD

**Issue by abryson-redhat** [redhat-cop/containers-quickstarts#41]
Have a client that has requested a builder image that would include rhel7+/openjdk8+/gradle4+.  They use gradle for their builds and are looking to transition a bunch of new projects to OpenShift, but need this new image.

**Comment by lpsantil** [comment]
Adding gradle to our openjdk image is not hard [0].

[0] https://github.com/pylejowdmn/springboot-gradle-s2i/blob/master/Dockerfile.rhel#L25-L29
