### ISSUE TITLE
failed to start gitlab-runner on okd3.11 for ubi7-gitlab-runner

### ISSUE THREAD

**Issue by gripenk** [redhat-cop/containers-quickstarts#415]
env:
oc version
oc v3.11.0+62803d0-1
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

openshift v3.11.0+c38d1eb-359
kubernetes v1.11.0+d4cacc0

GitLab version: 13.4.3

following the readme, values.yaml modified with the following values:
image: quay.io/redhat-cop/ubi7-gitlab-runner:latest
gitlabUrl: MY GITLAB URL
runnerRegistrationToken: MY TOKEN
runnerToken: MY TOKEN
rbac.serviceAccountName: gitlab-runner

log of GitLab runner pod

Registration attempt 1 of 30
--
  | Runtime platform                                    arch=amd64 os=linux pid=15 revision=e95f89a0 version=13.4.1
  | WARNING: Running in user-mode.
  | WARNING: The user-mode requires you to manually start builds processing:
  | WARNING: $ gitlab-runner run
  | WARNING: Use sudo for system-mode:
  | WARNING: $ sudo gitlab-runner...
  |  
  | Token specified trying to verify runner...
  | WARNING: If you want to register use the '-r' instead of '-t'.
  | ERROR: Verifying runner... is removed               runner=MiyxWPxi
  | PANIC: Failed to verify this runner. Perhaps you are having network problems
  | Registration attempt 2 of 30
  | Runtime platform                                    arch=amd64 os=linux pid=36 revision=e95f89a0 version=13.4.1
  | WARNING: Running in user-mode.
  | WARNING: The user-mode requires you to manually start builds processing:
  | WARNING: $ gitlab-runner run
  | WARNING: Use sudo for system-mode:
  | WARNING: $ sudo gitlab-runner...

**Comment by garethahealy** [comment]
@gripenk did you get this working? any more info you can provide?

CC @itewk as he was the original contributor of the runnner.

**Comment by itewk** [comment]
@gripenk @garethahealy no ideas. Never seen this error before. As this image is still working for us, i would guess maybe a configuration or gitlab configuration issue? have you researched on the gitlab side what the errors mean?
