### ISSUE TITLE
Do not recommend to use the MongoDB here, use the MongoDB operator in OperatorHub

### ISSUE THREAD

**Issue by alberttwong** [redhat-cop/containers-quickstarts#418]
I saw that there was some mongoDB scripts here.   I would recommend you archive the instructions here and use the MongoDB operator in OperatorHub.

**Comment by garethahealy** [comment]
@alberttwong ; am not sure if deprecating what is provided here is a good idea. for example, does the operator cover everything currently offered?

but, if you would like to raise a PR calling out that there is an operator in the mongo readme.md, I'll review/merge.

**Comment by alberttwong** [comment]
as far as I know yes....  however it's more steps to install and configure the operator.

**Comment by alberttwong** [comment]
https://github.com/redhat-cop/containers-quickstarts/pull/430

**Comment by pabrahamsson** [comment]
Fixed by #430
