### ISSUE TITLE
yum-config-manager does not function correctly with base images using RHEL 7.4

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/containers-quickstarts#42]
Images using RHEL 7.4 do not properly implement `yum-config-manager` as seen in this BZ

https://bugzilla.redhat.com/show_bug.cgi?id=1479388

Many of our images use `yum-config-manager` and will not be able to properly build images.

An alternate solution would be to enable repositories during the `yum install` command

**Comment by pabrahamsson** [comment]
Closing since a fix/workaround has been [merged](https://github.com/redhat-cop/containers-quickstarts/pull/43)
