### ISSUE TITLE
mvn command not found for jenkins-slave-mvn

### ISSUE THREAD

**Issue by Aaqib041** [redhat-cop/containers-quickstarts#442]
Hi ,

I tried building image using the Dockerfile for maven , but after running the image I got the maven error.

https://github.com/redhat-cop/containers-quickstarts/tree/fix/jenkins-slave-zap/jenkins-slaves/jenkins-slave-mvn

![image](https://user-images.githubusercontent.com/3587210/108557348-e3e4e800-7311-11eb-9560-712f74ca5d0e.png)

Please help

**Comment by garethahealy** [comment]
Have you tried the latest?
- https://github.com/redhat-cop/containers-quickstarts/tree/master/jenkins-agents/jenkins-agent-mvn

**Comment by Aaqib041** [comment]
Hi,

Yes , I am referring the same link.  

![image](https://user-images.githubusercontent.com/3587210/108560398-185aa300-7316-11eb-9bda-f1ed84fd7d72.png)

**Comment by garethahealy** [comment]
you'll need to provide more info, i've built and run the image:

```
$ docker build .
Sending build context to Docker daemon  6.144kB
Step 1/2 : FROM quay.io/openshift/origin-jenkins-agent-maven:4.6
4.6: Pulling from openshift/origin-jenkins-agent-maven
fecf0868d374: Pull complete
f7db571f3a05: Pull complete
0c983affa284: Pull complete
911e72d1d7d7: Pull complete
791696e2ff97: Pull complete
050d08c748fb: Pull complete
b9ef6a88723f: Pull complete
fc61c22b188e: Pull complete
Digest: sha256:1facb8e8f8867086a49ef6ac882755f02e748097b931578ace15538af2dd3eb3
Status: Downloaded newer image for quay.io/openshift/origin-jenkins-agent-maven:4.6
 ---> 4a7c2bb74ab4
Step 2/2 : ADD settings.xml $HOME/.m2/settings.xml
 ---> 384f6254bb5b
Successfully built 384f6254bb5b

$ docker run -it --entrypoint /bin/bash 384f6254bb5b
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
bash-4.4$ mvn --version
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
Apache Maven 3.6.2 (Red Hat 3.6.2-4)
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.10.0.9-0.el8_2.x86_64
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.19.121-linuxkit", arch: "amd64", family: "unix"
```

**Comment by Aaqib041** [comment]
Hi ,

I tried again by creating imagestream and buildconfig using the template from ---> https://github.com/redhat-cop/containers-quickstarts/blob/master/.openshift/templates/jenkins-agent-generic-template.yml

But updated buildConfig to refer **_quay.io/openshift/origin-jenkins-agent-maven:4.6_** instead of **_registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7_** ( which is defined in template ) . May be template need to update ?

With this change , mvn is working fine :)

Thank You for your help.

**Defined in template :** 
![image](https://user-images.githubusercontent.com/3587210/108570776-20234300-7328-11eb-9722-6445f27a40f2.png)


**Updated to :**
![image](https://user-images.githubusercontent.com/3587210/108570649-e3efe280-7327-11eb-8c53-8acbafce2d93.png)


**Testing Result :** 
![image](https://user-images.githubusercontent.com/3587210/108570544-9ffcdd80-7327-11eb-97e5-bee767d7873a.png)
