### ISSUE TITLE
build-s2i-play fails to build

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/containers-quickstarts#468]
see logs:
- https://gist.github.com/garethahealy/eb33cf9415e1ec60fc8cf1934f5826eb

**Comment by pabrahamsson** [comment]
Thank you for pointing this out @garethahealy 
Even if we get past those errors, it looks like the Activator is no longer available for download. I suggest the `build-s2i-play` be moved to deprecated.

**Comment by tylerauerbeck** [comment]
Closed by #476
