### ISSUE TITLE
remove nexus helm chart

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/containers-quickstarts#470]
this repo has a nexus chart:
- https://github.com/redhat-cop/containers-quickstarts/tree/master/nexus

and the helm repo also has a nexus chart:
- https://github.com/redhat-cop/helm-charts/tree/master/charts/sonatype-nexus

thoughts of deprecating / removing the one in this repo in favour of the helm-charts repo?

thoughts @pabrahamsson @springdo @tylerauerbeck ?

**Comment by pabrahamsson** [comment]
In general I think it makes sense to keep Helm charts in one repo and `helm-charts` seems like the proper place.

**Comment by tylerauerbeck** [comment]
Closed by #477
