### ISSUE TITLE
remove motepair

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/containers-quickstarts#471]
motepair upstream is dead:
- https://github.com/motepair/motepair

should we deprecate the chart in this repo?
- https://github.com/redhat-cop/containers-quickstarts/tree/master/motepair

there's quite a few different pair programming options now for vs-code/intellij/atom (https://teletype.atom.io/) - any reason to keep something dead in the repo?

thoughts @pabrahamsson @InfoSec812 ?

**Comment by pabrahamsson** [comment]
Yes, I think this should be moved to the deprecated folder.

**Comment by tylerauerbeck** [comment]
Closed by #475
