### ISSUE TITLE
move eap chart to helm repo

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/containers-quickstarts#472]
should we move the eap chart into the helm repo?
- https://github.com/redhat-cop/containers-quickstarts/tree/master/eap

i'd expect it to be "looked after" with all the other charts a bit better than in this repo

https://github.com/redhat-cop/helm-charts

thoughts @pabrahamsson @springdo @tylerauerbeck ?

**Comment by pabrahamsson** [comment]
Sounds good to me @garethahealy

**Comment by tylerauerbeck** [comment]
Closed by #478
