### ISSUE TITLE
Change name of published tekton task images

### ISSUE THREAD

**Issue by pabrahamsson** [redhat-cop/containers-quickstarts#484]
We currently have two Tekton task images for conftest & helm. They aren't yet being published to quay.io and before we do I'd suggest changing the name of these images to something more descriptive than [conftest](https://github.com/redhat-cop/containers-quickstarts/blob/master/.github/workflows/tekton-task-images-conftest-publish.yaml#L15) and [helm](https://github.com/redhat-cop/containers-quickstarts/blob/master/.github/workflows/tekton-task-images-helm-publish.yaml#L15).

Maybe `tekton-task-{conftest,helm}`?

cc: @ckavili @springdo @garethahealy

**Comment by garethahealy** [comment]
@pabrahamsson ; fine by me.
