### ISSUE TITLE
Update StatefulSet Quickstarts to Make Use of Native ImageStream Lookup

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/containers-quickstarts#50]
OpenShift 3.6 introduced mechanisms to reference ImageStreams from StatefulSets. 

https://docs.openshift.com/container-platform/3.6/release_notes/ocp_3_6_release_notes.html#ocp-36-container-orchestration

Update existing implementations to make use of this functionality

**Comment by pabrahamsson** [comment]
This has been addressed through #61, #69 & #72
