### ISSUE TITLE
Add Groovy Jenkins Slave

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/containers-quickstarts#57]

**Comment by sherl0cks** [comment]
Can be as simple as extending the existing mavens slave from openshift with a gradle installation

**Comment by etsauer** [comment]
@sherl0cks i assume there's not a red hat/centos source for gradle installs?

**Comment by sherl0cks** [comment]
https://access.redhat.com/downloads/content/groovy/1.8.9-8.el7_4/noarch/fd431d51/package

**Comment by garethahealy** [comment]
Closing as seems to be covered by:
- https://github.com/redhat-cop/containers-quickstarts/tree/master/jenkins-slaves/jenkins-slave-gradle
