### ISSUE TITLE
perform release to update images

### ISSUE THREAD

**Issue by itewk** [redhat-cop/containers-quickstarts#576]
There are currently critical findings for the https://quay.io/repository/redhat-cop/ubi8-asciidoctor?tab=tags&tag=latest image. Can we get another release to push a new version?

also, maybe set up a nightly build to constently be pushing a new latest?

**Comment by garethahealy** [comment]
@itewk ; we cant trigger an action manually (github needs an extra config that's not setup by default on the actions to do it) but if you want to raise a PR to add a schedule to:
- https://github.com/redhat-cop/containers-quickstarts/blob/master/.github/workflows/ubi8-asciidoctor-publish.yaml

am happy to review/merge.

**Comment by itewk** [comment]
@garethahealy ill do the PR for the schedule, but doesnt the version publishes come from tagging the repo?

**Comment by garethahealy** [comment]
@itewk the version should come from this file:
- https://github.com/redhat-cop/containers-quickstarts/blob/master/utilities/ubi8-asciidoctor/version.json

and the LATEST tag is auto-added via:
- https://github.com/redhat-cop/github-actions/blob/master/get-image-version/action.yml#L24-L40

**Comment by itewk** [comment]
@garethahealy yeah, i got my repos confused, i work in another container repo that publishes images based on repo tags.

put in PR: https://github.com/redhat-cop/containers-quickstarts/pull/577
