### ISSUE TITLE
jenkins-agents/jenkins-agent-zap dockerbuild doesn't work anymore

### ISSUE THREAD

**Issue by SylivanKenobi** [redhat-cop/containers-quickstarts#587]
`jenkins-agents/jenkins-agent-zap` dockerbuild doesn't work anymore

Webswing isn't available anymore

`$ curl -sL https://bitbucket.org/meszarv/webswing/get/2.5.10.tar.gz`
`The requested repository either does not exist or you do not have access. If you believe this repository exists and you have access, make sure you're authenticated.`

**Comment by cookcodeblog** [comment]
Yeah, have same issue, seems the whole repository https://bitbucket.org/meszarv/webswing doesn't exist anymore.

**Comment by eformat** [comment]
@pabrahamsson i see zap Dockerfile has moved to here

https://github.com/zaproxy/zaproxy/blob/main/docker/Dockerfile-stable#L24-L34

and older version not publicly available it seems

![Screenshot from 2022-11-05 10-29-14](https://user-images.githubusercontent.com/712608/200092687-924cacef-e8da-4139-a7ae-702f1d355bc1.png)

**Comment by pabrahamsson** [comment]
@SylivanKenobi @cookcodeblog @eformat I've opened up #589 in an attempt to fix this issue. It builds locally but I could use some help with testing.

**Comment by eformat** [comment]
rogga @pabrahamsson  .. i will give it a spin .. but need a bit of time

**Comment by eformat** [comment]
hi @pabrahamsson .. testing looks good.. ship it !

![Screenshot from 2022-11-07 08-23-52](https://user-images.githubusercontent.com/712608/200198472-145a161c-e021-401a-ac4e-1fc6e7e58306.png)

![Screenshot from 2022-11-07 08-24-10](https://user-images.githubusercontent.com/712608/200198473-ff9b8aff-ec43-4fe5-84e7-f73756e4f2e5.png)
