### ISSUE TITLE
Add Gitlab openshift-applier Inventory

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/containers-quickstarts#65]
Parts of this live in labs-ci-cd today: https://github.com/rht-labs/labs-ci-cd/tree/master/openshift-templates/gitlab

**Comment by makentenza** [comment]
@sherl0cks same question I did on the Gogs issue.

The existing PR for Gitlab CE: https://github.com/redhat-cop/containers-quickstarts/pull/67

**Comment by sherl0cks** [comment]
https://github.com/redhat-cop/containers-quickstarts/issues/66#issuecomment-368693981

IMHO - I wouldn't hold the PR up for an inventory, but that isn't my call here.

**Comment by makentenza** [comment]
@sherl0cks this is done now in case you can review the PR

**Comment by pabrahamsson** [comment]
Resolved with #67, closing.
