### ISSUE TITLE
Add Gogs openshift-applier Inventory

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/containers-quickstarts#66]
Parts of this live in labs-ci-cd today: https://github.com/rht-labs/labs-ci-cd/tree/master/openshift-templates/gogs

**Comment by makentenza** [comment]
@sherl0cks do you want to add applier required inventory sample to the existing PR?

https://github.com/redhat-cop/containers-quickstarts/pull/68

**Comment by sherl0cks** [comment]
My understanding is @etsauer @sabre1041 want to move to a point where everything in COP repos is appliable. In general, I think that is a good idea, but I'm not a maintainer here so I need to delegate to their opinions.

**Comment by etsauer** [comment]
@sherl0cks @makentenza yeah I would go ahead and add it to the existing PR.

**Comment by makentenza** [comment]
@etsauer @sherl0cks done
