### ISSUE TITLE
deprecate jenkins-arachni

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/containers-quickstarts#695]
arachni cant be updated past the current version, as it requires a RHEL9 base:
- https://github.com/redhat-cop/containers-quickstarts/pull/691

the project is also no longer active anymore:
- https://github.com/Arachni/arachni?tab=readme-ov-file#notice
- https://ecsypno.com/pages/arachni-web-application-security-scanner-framework

but is used by:
- https://rht-labs.com/enablement-docs/#/4-an-enslaved-hope/README?id=_1b-arachni-scan

**Comment by garethahealy** [comment]
@ckavili @springdo @eformat since you are the main consumers for arachni or have used it in the past. thoughts?

**Comment by eformat** [comment]
yeah - time to deprecate fully i think - since we use ACS/Stackrox nowdays

**Comment by garethahealy** [comment]
@eformat are there any other jenkins-agents you guys don't use anymore and can be deprecated?
