### ISSUE TITLE
Can the Java-S2I image include a bill of materials, including a usage walkthrough more similar to the WebSphere Liberty image?

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/containers-quickstarts#7]
cc: @sabre1041

**Comment by sabre1041** [comment]
@etsauer ill use content from the [PR](https://github.com/redhat-cop/containers-quickstarts/pull/5) and add this in over the next few days

**Comment by sabre1041** [comment]
Bill of Materials were added
