### ISSUE TITLE
Migrate Jenkins Slave from Labs CI/CD

### ISSUE THREAD

**Issue by sherl0cks** [redhat-cop/containers-quickstarts#78]
Also remove ansible stacks slave as that is out of date.

Per discussion with @sabre1041 @etsauer

**Comment by springdo** [comment]
Happy to take on this work guys. I'll fork the repo and start moving my outstanding PR from labs-ci-cd for merging here.

**Comment by pabrahamsson** [comment]
Fixed by #80
