### ISSUE TITLE
Repo Needs a New README

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/containers-quickstarts#81]
We need to define what a "container quickstart" is. I see this looking similar to https://github.com/redhat-cop/container-pipelines/blob/master/README.md

Some ideas for requirements:

- CentOS (or other community base) for hosting on public registry (currently dockerhub)
- RHEL (or Atomic) base for enterprise consumption
- Applier inventory that proves functionality of the quickstart
- README that includes:
  - **Requirements & Assumptions** section
  - **Quickstart** Instructions for getting it up and running 
  - **Configuration** section that talks about any customization options
  - **Verification** instructions that show the quickstart is working as expected
  - **Tear Down** commands

**Comment by pabrahamsson** [comment]
@etsauer can we close this issue based on #92
