### ISSUE TITLE
How to do CI in this repo

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/containers-quickstarts#82]
Some initial thoughts on how we can add some level of CI to this repository.

1. Assume all quickstarts include an applier inventory (#81 )
2. Set up a travis build to kick off a test of each quickstart in the CASL clusters
  - store a service account secret in an encrypted key in travis
  - use oc (binary in repo?) to deploy a pipeline to openshift
  - utilize 'make-applier-projects-unique' role to prefix all namespaces

**Comment by sabre1041** [comment]
@etsauer it would be good if we can use this as a usecase to build a reference architecture around automated acceptance testing. 

A couple things that are specific to this repository:

* For each PR, do we intend to test every quickstart or only those that are part of the PR
* Refarding your comment on the OC client, we should be downloading them as a `before_install` task. All clients are available [here](https://mirror.openshift.com/pub/openshift-v3/clients/)
* What is the success criteria? pods running successfully?  builds completed successfully?

**Comment by pcarney8** [comment]
It looks like the card in Trello was archived, but we definitely still need this. So I'm bumping this thread with the hopes that I'll follow up on setting up a travis build

**Comment by garethahealy** [comment]
@etsauer is this OK to be closed? or is there more prow related work that needs to be tracked via this issue?
