### ISSUE TITLE
Unable to mount volumes for pod "zookeeper-0_zookeeper.."

### ISSUE THREAD

**Issue by ale123ga** [redhat-cop/containers-quickstarts#88]
Dear all,

I followed the instruction reported on the readme, but it seems that during the deployment of zookeeper-0, the pod fails to mount the volume. Into the event log i got this error:

`
   Unable  to mount volumes for pod  "zookeeper-0_zookeeper(2a0c3a72-3727-11e8-8e85-005056a31518)": timeout  expired waiting for volumes to attach/mount for pod  "zookeeper"/"zookeeper-0". list of unattached/unmounted  volumes=[datadir]
`

` MountVolume.SetUp failed for volume "pv0004" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/origin/openshift.local.volumes/pods/2a0c3a72-3727-11e8-8e85-005056a31518/volumes/kubernetes.io~nfs/pv0004 --scope -- mount -t nfs lv170170.vtlab.local:/nfsshare/pv0004 /var/lib/origin/openshift.local.volumes/pods/2a0c3a72-3727-11e8-8e85-005056a31518/volumes/kubernetes.io~nfs/pv0004 Output: Running scope as unit run-22561.scope. mount.nfs: No route to host `

Do you have idea how I can solve the problem? Thanks in advance.

**Comment by pabrahamsson** [comment]
@ale123ga,
The error you're getting seems unrelated to deploying Zookeeper and I would expect the same error for any pod using persistent storage. The `mount.nfs: No route to host` suggests there's an issue with the [NFS backed persistent storage](https://docs.openshift.com/container-platform/3.9/install_config/persistent_storage/persistent_storage_nfs.html) in your cluster.

**Comment by ale123ga** [comment]
Dear @pabrahamsson ,

As regards the creation of pv, I used the same requirements of access, capacity, etc. as specified in the [guide](https://github.com/redhat-cop/containers-quickstarts/tree/master/zookeeper). However, it seems that only "datadir-zookeeper-0" is bounded with the pv0004 as shown below:

NAME      CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM                             STORAGECLASS   REASON    AGE
pv0004    1Gi        RWO,RWX       Recycle         Bound       zookeeper/datadir-zookeeper-0                              1d
pv0005    2Gi        RWO,RWX       Recycle         Available                                                              1d
pv0006    3Gi        RWO,RWX       Recycle         Available                                                              1d

The same does not happen with the other pods...Shall I write a specific claim? Do you have any recommendation?
I create the pv using the following:
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /nfsshare/pv0004
    server: lv170170.vtlab.local 
  persistentVolumeReclaimPolicy: Recycle

Thanks in advance again for any further help.

**Comment by pabrahamsson** [comment]
@ale123ga the zookeeper quickstart has been deprecated in favor of the [Strimzi project](http://strimzi.io/).
