### ISSUE TITLE
Broken Dockerfiles depending on CentOS7

### ISSUE THREAD

**Issue by burigolucas** [redhat-cop/containers-quickstarts#899]
Due to the CentOS Linux 7 End of Life: June 30, 2024, containers depending on CentOS7 base image do not build. See, for example: https://github.com/redhat-cop/containers-quickstarts/blob/3c9a63a1cc2ee9bb888b7770173648fcd75e7794/jenkins-agents/jenkins-agent-zap/Dockerfile#L1

**Comment by garethahealy** [comment]
@burigolucas the example (jenkins-agent-zap) isn't maintained anymore

**Comment by burigolucas** [comment]
Thanks for the quick feedback @garethahealy, I have noticed this dependency on a repo from rh-labs using the chart redhat-cop/helm-charts/charts/jenkins. I will report this braked dependency there as `wontfix` then.
