### ISSUE TITLE
Jenkins Image Management Slave Template for OpenShift Origin

### ISSUE THREAD

**Issue by viv816** [redhat-cop/containers-quickstarts#94]
Hi,

Is there any Skopeo template available for OpenShift Origin cluster? 

I want to deploy a Skopeo component on Origin cluster and have a capability of moving images from  OpenShift Origin cluster's docker registry to OpenShift Enterprise cluster's docker registry.

Thank you in advance.

**Comment by etsauer** [comment]
hey @viv816 sorry for the long delay. there shouldn't be much different skopeo-wise between OpenShift Origin to OpenShift Enterprise to my knowledge. The skopeo slave in this repo should work for that. I would also suggest checking out this [sample pipeline](https://github.com/redhat-cop/container-pipelines/tree/master/multi-cluster-spring-boot) that uses skopeo to promote an image between clusters for an example.

One other thing you may want to pay attention to is that OpenShift is adopting a skopeo-style functionality natively in oc, called `oc image mirror`. We are looking at migrating most of our skopeo functionality over to that in the next month or two. See this issue for some more background
https://github.com/openshift/jenkins/issues/632

**Comment by pabrahamsson** [comment]
Closing based on response from @etsauer, @viv816 feel free to re-open if necessary.
